### ISSUE TITLE
'Package for QField' is greyed out

### ISSUE THREAD

**Issue by blackkolodets** [opengisch/qfieldsync#442]
Hi, I am unable to package a small project for QField as the option is greyed out. Any pointers? Thanks

**Comment by Ipickedausername** [comment]
When you pack a project with Qfield sync, the current shown project is replaced by the one created in C: 
You can still work (but you should not) on this "packed project" but you can no longer pack again. 

I don't understand why the packed project is opened instead of keeping the current project.

Maybe this is your situation ? You packed your project once, and you try to reopen the project using the folder of the packed one ?
