### ISSUE TITLE
[Bug] Qfield sync cannot link/relink some shape file 

### ISSUE THREAD

**Issue by Growth64** [opengisch/qfieldsync#464]
QGIS: 3.22
Qfield sync: 4.1.1
Qfield: 2.2.1

When I transfert a projet to qfield with the Qfield_sync addon it showes me this:
https://zupimages.net/viewer.php?id=22/34/lug5.png
(This is new since last week)

On parameters, we can see this 
https://zupimages.net/viewer.php?id=22/34/lgu2.jpg

So when I load the projet on qfield, it cant load 2 shapes.
https://zupimages.net/viewer.php?id=22/34/u7ty.jpg

This 2 shapes arent listing on the warning list but "direct acces to data source" and not "copy" like others

Thuesday 18 August: Only the "Fumee" shape cannot load... the "Enquete" ones worked well

**Comment by m-kuhn** [comment]
Are the 2 affected shapefiles on a network drive? QField does not have access to your network drives (i.e. "direct access to data source" will not work)

A couple of notes:

- Better use geopackage than shapefile. Support for shapefiles is not guaranteed.
- Filenames must not contain special characters (like `é` or `ê`), that's why the warning shows up
