### ISSUE TITLE
Impossible to install QfieldSync 

### ISSUE THREAD

**Issue by KamKamille** [opengisch/qfieldsync#521]
Hello, 

I used Qfield since few mounths and I had no problem. But yesterday, I had an error and I cannot use anymore Qfield, I tried to install again the extension but I had the message of error below (in the image also) : 

_

> Impossible de charger l'extension 'qfieldsync' provoque une erreur lors de l'appel à sa méthode classFactory() 
> 
> ImportError: cannot import name 'TypedDict' from 'typing' (C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\typing.py)

_ 

![Photo_prob](https://github.com/opengisch/qfieldsync/assets/133862747/a97306e4-b848-4895-bca8-7f1c17da9630)

I tried in an other computer and with an other version of QGIS but it's the same message of error. 

Do you know any solution ? 

Thanks in advance and sorry for my pity english ;) 

Camille

**Comment by suricactus** [comment]
Hello @KamKamille . The reason for this error is because you are using QGIS with old python in it. Can you please put a copy-paste/screenshot of your QGIS `Help -> About` dialog with all the software verions?

Note that it is always recommended you use supported QGIS versions, which nowadays are QGIS 3.30 and QGIS 3.28 LTR.
