### ISSUE TITLE
Date: Unknown data type QDateTime. Not using type affinity for the field.

### ISSUE THREAD

**Issue by xyago** [opengisch/qfieldsync#74]
We have a field like date type, in the database and we have this error.

Is there a solution?
Thanks!!

**Comment by m-kuhn** [comment]
This is because in sqlite there is no datetime field. This is more an information (which can be savely ignored) than an error. We should probably hide this message (which comes from QGIS offline editing) away, it's mostly confusing.
If you experience issues with those fields, please reopen this issue.
