### ISSUE TITLE
Copy action for geopackage in project configuration not available

### ISSUE THREAD

**Issue by soester** [opengisch/qfieldsync#85]
[project configuration]
Copy action is not available for layers stored in geopackage.

When creating an offline project, it would be great to be able to copy data stored in geopackages.
So raster or vector data could be used as background in offline projects. For shp files this option is available.

Available actions for raster layers (geopackage):
- no action
- remove

Available actions for vector layers (geopackage):
- no action
- offline editing
- remove

edit: QGIS 3.2.2, Qfieldsync 3.0.2

**Comment by saemiw** [comment]
I confirm this with qfieldsync 3.0.3. and QGIS 3.2.

Hint to the developers. I made a (German) note to my self a long time ago that explains that it is sometimes possible. I just post this to give you a starting point when looking for reasons (in case its not obvious to you anyway): 
_Wenn ein Layer als geopackage exportiert wird (save as) und dann im Layer name ein Eintrag gemacht wird, wird das geopackage nicht als file-based-Format von QFieldSync erkannt. Entsprechend steht beim Export die Option „copy“ nicht zur Verfügung. Es wäre schön, wenn alle geopackages auch im „nicht offline“-Modus verwendet werden könnten. -> Doch das ist möglich, es muss aber der als 1. Hinzugefügte Layer ausgewählt werden. Dort gibt es die Option „copy“. Dieses copy wird dann auf das geopackage angewendet. Für alle anderen Layer innerhalb dieses geopackages muss die Option „no action“ angekreuzt werden. Am Schluss stehen alle layer des geopackages zur Verfügung, auch für nicht offline-editing._

**Comment by saemiw** [comment]
More precision on this issue: Maybe in a first step implement that geopackages can use the copy function for all layers of one geopackage. If you have some layers that need to be edited offline and some that don't need to be edited store them in two different geopackges (one is set offline and one is copied). Having those two kind of layers mixed in one geopackage seems to complicate things unnecessaraly.

**Comment by saemiw** [comment]
@m-kuhn as I think you have been working on this (part of our offer).

There is now an option "copy" for geopackage layers. Cool.

But there is the following problem when you apply this function to a geopackage that containts multiple layers.
- The layer to copy ("schneesperling...sonstwelchepunkte") contains now 13 instead of the original 2 points. The origin of all these points is not clear to me (are the lines in there). I'd expect that this layer only contains the to original points.
- GOOD: The "lines" are as expected removed.
- GOOD: The "pointcountbirds" are as expected set offline
![prasentation1](https://user-images.githubusercontent.com/20398621/53819227-cd4cf700-3f69-11e9-81f5-62add4d1bde6.png)

I tested with qfieldsync 3.1.1 and qgis 3.4.4

**Comment by m-kuhn** [comment]
Can you send us the source project, that looks very weird indeed.

**Comment by saemiw** [comment]
Of course, you find the project below (it does not contain any meaningful data, so don't be shocked).
[Schneesperling.zip](https://github.com/opengisch/qfieldsync/files/2931911/Schneesperling.zip)
